#index:
#    path: /
#    controller: App\Controller\DefaultController::index

triangle:
    path: /triangle
    controller: App\Controller\CalculateController::triangle

circle:
    path: /circle
    controller: App\Controller\CalculateController::circle